<?$APPLICATION->IncludeComponent(
	"intec.universe:main.widget",
	"contact.1",
	Array(
		"ADDRESS_CITY" => "Москва",
		"ADDRESS_SHOW" => "Y",
		"ADDRESS_STREET" => "ул. Свободы д.61 к.1",
		"BLOCK_SHOW" => "Y",
		"BLOCK_TITLE" => "Наши контакты",
		"BLOCK_VIEW" => "over",
		"CACHE_TIME" => "3600000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "contact.1",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONSENT_URL" => "",
		"EMAIL_SHOW" => "Y",
		"EMAIL_VALUES" => array(0=>"info@afforto.ru",1=>"",),
		"FORM_BUTTON_TEXT" => "Заказать звонок",
		"FORM_ID" => "1",
		"FORM_SHOW" => "Y",
		"FORM_TEMPLATE" => ".default",
		"FORM_TITLE" => "Заказать звонок",
		"INIT_MAP_TYPE" => "MAP",
		"MAP_API_KEY" => "a95a9b3d-f0f0-40c6-8b16-679851ba2bfa",
		"MAP_COMPOSITE_FRAME_MODE" => "A",
		"MAP_COMPOSITE_FRAME_TYPE" => "AUTO",
		"MAP_CONTROLS" => array(0=>"ZOOM",1=>"MINIMAP",2=>"TYPECONTROL",3=>"SCALELINE",),
		"MAP_MAP_DATA" => "a:4:{s:10:\"yandex_lat\";d:55.85395958729448;s:10:\"yandex_lon\";d:37.44990160246011;s:12:\"yandex_scale\";i:18;s:10:\"PLACEMARKS\";a:1:{i:0;a:3:{s:3:\"LON\";d:37.450022169312;s:3:\"LAT\";d:55.854089541177;s:4:\"TEXT\";s:31:\"ул. Свободы д.61 к.1\";}}}",
		"MAP_MAP_ID" => "Аффорто",
		"MAP_OPTIONS" => array(0=>"ENABLE_SCROLL_ZOOM",1=>"ENABLE_DBLCLICK_ZOOM",2=>"ENABLE_DRAGGING",),
		"MAP_OVERLAY" => "N",
		"MAP_VENDOR" => "yandex",
		"PHONE_SHOW" => "Y",
		"PHONE_VALUES" => array(0=>"+7 (495) 740 80 73",1=>"",),
		"SETTINGS_USE" => "N",
		"WIDE" => "Y"
	)
);?>